config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]  
  end
  
  resources :charges, only: [:new, :create]
  
  get '/downgrade', to: 'charges#downgrade'
  delete '/downgrade', to: 'charges#destroy'
  
  devise_for :users
  
  root to: "home#index"
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :wikis
  has_many :collaborators
  has_many :collab_wikis, class_name: "Wiki", through: :collaborators, source: :wiki
  
  before_save { self.role ||= :standard }
  
  enum role: [
    :standard,
    :premium,
    :admin
  ]
  
  def set_admin 
    self.admin!
  end

  def set_standard
    self.standard!
  end
  
  def set_premium
    self.premium!
  end
  
  def owns?(arg)
    self.id == arg.user_id
  end
  
  def premium_permission?
    self.premium? || self.admin?
  end

  def make_wiki_public
    wikis.each do |w|
      w.update_attributes(private: false); 
    end
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  friendly_id :title, use: :slugged
  
  private
    def should_generate_new_friendly_id?
      slug.blank? || title_changed?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
    
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
    
  def authorize_user
     unless user_signed_in?
       redirect_to new_user_session_path
     end
  end
    
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    before_action :authorize_user
    before_action :new?, only: [:new, :create]
    before_action :downgrade?, only: [:downgrade]
    
    def create
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
        
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 10_00,
            description: "Rubypedia Membership - #{current_user.email}",
            currency: 'usd'
        )
        
        current_user.premium!
        redirect_to wikis_path
        
        rescue Stripe::CardError => e
        flash[:alert] = e.message
        redirect_to new_charge_path 
    end
    
    def new
       @stripe_btn_data = {
         key: "#{ Rails.configuration.stripe[:publishable_key] }",
         description: "Rubypedia Membership - #{current_user.username}",
         amount: 10_00
       }
    end
    
    def edit 
        
    end
    
    def destroy
        if current_user.standard!
            current_user.make_wiki_public
            redirect_to root_path
        end
    end
    
    
    
    def new?
        if current_user.standard? 
            true
        else
            redirect_to downgrade_path
        end
    end
    
    def downgrade?
       if current_user.premium?
           true
       else
           redirect_to new_charge_path
       end
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Wiki.find(params[:id]).collaborators.new
  end
  
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.new
    @user = params[:collaborator][:user]
    if User.find_by_email(@user) != nil
      @collaborator.user_id = User.find_by_email(@user).id
      if !User.find(@collaborator.user_id).collab_wikis.include?(@wiki)
        if User.find_by_email(@user) != current_user
          @collaborator.save
          redirect_to edit_wiki_url(params[:wiki_id]), :alert => "User was added"
        else
          redirect_to edit_wiki_url(params[:wiki_id]), :alert => "You are already a Collaborator"
        end
      else
        redirect_to edit_wiki_url(params[:wiki_id]), :alert => "User is already a Collaborator"
      end
    else
      redirect_to edit_wiki_url(params[:wiki_id]), :alert => "User does not exist"
    end
  end
  
  def destroy
    @user = params[:id]
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.find_by_user_id(@user)
    authorize @collaborator
    if @collaborator.destroy
      redirect_to @wiki
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
   before_action :authorize_user, except: [:index, :show]
   
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    @collaborators = @wiki.collaborators.all
    @collab_users = []
    @collaborators.each do |f|
      @collab_users << User.find(f.user_id)
    end
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = current_user.wikis.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    if current_user.premium_permission?
      @wiki.private = params[:wiki][:private]
    else
      @wiki.private = false;
    end
    @wiki.user = current_user 
    
    if @wiki.save
      redirect_to @wiki
    else
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end
  
   def update
     @wiki = Wiki.friendly.find(params[:id])
     
     authorize @wiki
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
     if current_user.premium_permission?
      @wiki.private = params[:wiki][:private]
     else
      @wiki.private = false;
     end
  
     if @wiki.save
       redirect_to @wiki
     else
       render :edit
     end
   end  
  
  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      redirect_to wikis_path
    else
      redirect_to wiki(params[:id])
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        markdown = Redcarpet::Markdown.new(
            Redcarpet::Render::HTML.new(
                prettify: true,
                hard_wrap: true
                ),
            fenced_code_blocks: true,
            strikethrough: true,
            autolink: true,
            tables: true,
            underline: true,
            highlight: true,
            quote: true,
            footnote: true
            )
        markdown.render(text).html_safe
    end
    
end

app/helpers/charges_controller_helper.rb
module ChargesControllerHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
    
end

app/views/charges/downgrade.html.haml
.container
  .row.flex-column
    %h2 Do you want to downgrade back to a Standard User
    %h3 All settings will return to Standard User settings
    .flex
      = link_to 'No Way!', root_path, class: "btn btn-success item"
      = link_to 'Downgrade', downgrade_path, :method => :delete, data: { confirm: 'Are you sure you want to return to a standard user? All private Wikis will be returned to Public.' }, class: "item"

app/views/charges/new.html.haml
.container
  .jumbotron.flex-column
    %h1 Upgrade to a Premium User for just $10
    %h2 and create private wiki's that only you, and your friends can touch!
    .align-right
      = form_tag charges_path do
        %script.stripe-button{"data-amount" => @stripe_btn_data[:amount], "data-description" => @stripe_btn_data[:description], "data-key" => @stripe_btn_data[:key], :src => "https://checkout.stripe.com/checkout.js"}

app/views/home/index.html.haml
.container
  .col-md-10
    .jumbotron
      %h2 Rubypedia
      %p Join in and collaborate on community-sourced content!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.bg-faded.fixed-top
        %h3= link_to "Home", root_path, class: "align-left close-links", id: "home"
        - if !user_signed_in?
          %h4
            = link_to "Sign Up", new_user_registration_path, class: "align-right"
            = link_to "Sign In", new_user_session_path, class: "align-right"
        - else
          %h4.align-right= link_to "Sign Out", destroy_user_session_path, :method => :delete
          - if current_user.standard? == false
            %h4.align-right.role= link_to "#{current_user.role} user", downgrade_path
          - else
            %h4= link_to "Upgrade to Premium!", new_charge_path, class: "align-right role"
          %h4.align-right= current_user.username
        %form.form-inline.align-right.search
          %input.form-control.mr-sm-2{:placeholder => "Search", :type => "text"}/
          %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
    .row
      #sidebar.col-md-2
        .nav.nav-stacked
          %h1= link_to "Wikis", wikis_path
          %h4= link_to "Create a Wiki", new_wiki_path
          - if user_signed_in?
            - if current_user.wikis.empty?
              %h3 You have no wikis
            - else
              %h3 Your Wikis
              - current_user.wikis.each do |w|
                %h4
                  \-#{link_to w.title, wiki_path(w.slug)}-
      = yield

app/views/wikis/edit.html.haml
.container
  .wiki
    .row.col-md-8
      = form_for @wiki do |f|
        .field.input-group.wiki-title
          = f.label :title
          = f.text_field :title, autofocus: true, class: "form-control"
        .wiki-body
          = f.label :body
          = f.text_area :body, class: "form-control wiki-body"
        - if policy(@wiki).private_wiki?
          .field.radio.wiki-private
            = f.check_box :private
            = f.label :private
        - else
          .field.radio.wiki-private
            = f.check_box :private, disabled: true
            = f.label :private
            (Upgrade to Premium!)
        .wiki-save
          = f.submit "Save", class: "btn"
  - if policy(@wiki).private_wiki?
    .wiki
      .row.col-md-8
        = form_for [@wiki, Collaborator.new] do |f|
          .field.input-group.wiki-collab
            .alert-info
              = flash[:alert]
            = f.email_field :user, placeholder: :Email
            = f.submit "Add Collaborator", class: "btn btn-success"

app/views/wikis/index.html.haml
.container
  .col-md-10
    - @wikis.each_with_index do |w, i|
      .row
        %h3= link_to w.title, wiki_path(w)
        %p= truncate(w.body, length: 400)

app/views/wikis/new.html.haml
.container
  .wiki
    = form_for @wiki do |f|
      .field.input-group.wiki-title
        = f.label :title
        = f.text_field :title, autofocus: true, class: "form-control"
      .wiki-body
        = f.label :body
        = f.text_area :body, class: "form-control wiki-body"
      - if current_user.premium? || current_user.admin?
        .field.radio.wiki-private
          = f.check_box :private
          = f.label :private
      - else
        .field.radio.wiki-private
          = f.check_box :private, disabled: true
          = f.label :private
          (Premium users)
      .wiki-save
        = f.submit "Save", class: "btn"

app/views/wikis/show.html.haml
.container
  .row
    .col-xs-12.col-md-6.col-lg-8.col-xl-10
      %h1= @wiki.title
      %p= markdown(@wiki.body)
    .col-md-12.col-lg-4.wiki-info
      .info-box
        %h3
          Created By #{@wiki.user.username}
        %h4
          Private Wiki: #{@wiki.private}
        %h5
          %em
            Created at #{@wiki.created_at}
        %h3 Collaborators:
        .info-collaborators
          %p
            - @collab_users.each do |w|
              = w.username + ", "
              - if user_signed_in?
                - if policy(@wiki).destroy?
                  = link_to 'delete', wiki_collaborator_path(@wiki, w.id), :method => :delete, class: "delete", data: { confirm: 'Are you sure you want to remove this user as a collaborator' }
        .buttons
          - if user_signed_in?
            - if policy(@wiki).update?
              = link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-info'
            - if policy(@wiki).destroy?
              = link_to "Delete", @wiki, method: :delete, class: "delete", data: { confirm: 'Are you sure you want to delete the wiki?' }